### PR TITLE
adding Ogremoch from POTA

### PR DESCRIPTION
**Pull request by grandchefpanda**
Need to add a source. Sklore can you check the file name if it is ok for you, if yes can you add a source for Prince of the apocalypse POTA

### CODE REVIEW

**Comment by LordMorin** [comment]
PotA is Elemental Evil, which I believes is already there as a source.

**Comment by grandchefpanda** [comment]
Can you check also if some text must be removed, I have already remove some things but I kept Regional effects, don't know if we can keep it

**Comment by grandchefpanda** [comment]
The player companion is there but not the sourcebook

**Comment by Sklore** [comment]
I'll add it today. I was trying to determine the correct place for EEPC. 

I'm thinking I made a POTA under adventures and put both books under it.

**Comment by grandchefpanda** [comment]
some part of EEPC is also in PotA like the genasi and spells

**Pull request merged**
