### PR TITLE
Added spells for EEPC

### PR DESCRIPTION
**Pull request by xdy**
Placeholder everywhere, classes for spells added.

### CODE REVIEW

**Comment by Sklore** [comment]
You can leave spell mechanics in btw.  It's the descriptive fluff text that can't be included.

**Comment by xdy** [comment]
Yeah, I'll probably do a description pass later, but right now I proritize
getting the basics up for what I need as a player or DM. :)

**Comment by xdy** [comment]
I should have done this in a branch, shouldn't I? (Habits from svn at work, where we avoid branches like the plague. Should have gone with memories of the branch-happy days of clearcase I guess. :)
Oh well, live and learn. Future pull requests will come from branches.
For now, I've added some spell descriptions and a race to EEPC. Also added a race to SCAG.

**Comment by Sklore** [comment]
Doing the cleanup work on the sources now.

**Comment by Sklore** [comment]
To Do: Deep Gnome

**Pull request merged**
