### PR TITLE
Unearthed Arcana - Warlock & Wizards

### PR DESCRIPTION
**Pull request by TheEnthusiast**
- New Warlock Otherworldly Patron - Hexblade
- New Warlock Otherworldly Patron - The Raven Queen
- 20 New Warlock Eldritch Invocations
- New Wizard Arcane Tradition - Lore Mastery

### CODE REVIEW

**Comment by Sklore** [comment]
Mate you are bloody quick at getting these done.thank you!

**Comment by TheEnthusiast** [comment]
Too much free time, I'm afraid😀

I've learned a few things with temhppools, I intend to implement them in other places, like the Inspiring Leader feat.

-------- Mensagem Original --------
De:Daplunk <notifications@github.com>
Enviado em:Fri, 17 Feb 2017 00:37:56 -0200
Para:Sklore/HL_DD_5e_Colab <HL_DD_5e_Colab@noreply.github.com>
Cc:TheEnthusiast <ps3nerobr@gmail.com>,State change <state_change@noreply.github.com>
Assunto:Re: [Sklore/HL_DD_5e_Colab] Unearthed Arcana - Warlock & Wizards (#590)

**Comment by LordMorin** [comment]
I just learned about this UA update and started working on it. Now I don't
have to (unless it conflicts with other unrelated stuff I already have).

**Comment by LordMorin** [comment]
Ok, I must be missing something. I download the .user file but when I try to load it, I get the following error:

> Hero Lab was forced to stop compilation after the following errors were detected:
> 
> File: COM_5ePack_UA - WarWiz.user (line 7) - Invalid top-level element tag

**Comment by TheEnthusiast** [comment]
I created it with core 2.1 already installed, if it helps.


-------- Mensagem Original --------
De:LordMorin <notifications@github.com>
Enviado em:Fri, 17 Feb 2017 02:41:26 -0200
Para:Sklore/HL_DD_5e_Colab <HL_DD_5e_Colab@noreply.github.com>
Cc:TheEnthusiast <ps3nerobr@gmail.com>,State change <state_change@noreply.github.com>
Assunto:Re: [Sklore/HL_DD_5e_Colab] Unearthed Arcana - Warlock & Wizards (#590)

**Comment by LordMorin** [comment]
Which additional files do I need to grab and install?

**Comment by TheEnthusiast** [comment]
As far as I know, none. But there's one or two invocations requiring the Seeker patron, so you would need the the faithful file as well. You should have it already.

-------- Mensagem Original --------
De:LordMorin <notifications@github.com>
Enviado em:Fri, 17 Feb 2017 12:33:52 -0200
Para:Sklore/HL_DD_5e_Colab <HL_DD_5e_Colab@noreply.github.com>
Cc:TheEnthusiast <ps3nerobr@gmail.com>,State change <state_change@noreply.github.com>
Assunto:Re: [Sklore/HL_DD_5e_Colab] Unearthed Arcana - Warlock & Wizards (#590)

**Comment by LordMorin** [comment]
Hmmm . . . so I should onlu need to add the one .user file?

COM_5ePack_UA - WarWiz.user

If so, I don't know what is causing the error. 

It would be nice to see if I am the only one who currently has an issue with it. Since you created the file, it would need to be someone other than yourself.

**Comment by Sklore** [comment]
I'll test in a bit.

**Comment by LordMorin** [comment]
Thanks Sklore.

**Comment by Sklore** [comment]
Everything is working fine on this end. Did you download the whole community pack or just the single file?

**Comment by LordMorin** [comment]
Just the single file. I couldn't find where to download the pack as a whole and I couldn't figure out which files I needed beyong the obvious.

**Comment by Sklore** [comment]
Try this: https://github.com/Sklore/HL_DD_5e_Colab/archive/master.zip

Usually when we add new files we update the files that add the menu stuff also. Although I can't think why that would stop it from working... although I'm a few beers down right now so....

**Comment by LordMorin** [comment]
Well, whichever file I missed, it's all working now. Still had to leave out the new UA Artificer since it conflicts with my own version. :)

**Comment by Sklore** [comment]
You shouldn't be conflicting unless you are copying our names.

**Comment by LordMorin** [comment]
I added my artificer when HL first put out 5E, so the Community Pack copied me. :)

When I can I plan to copy the Community Pack's .user file and change the Conflicting tags. I, and my group, have too many artificer for me to change mine.

I still remember the nightmares I caused myself when put out the updated Mystic handbook. I changed my version and it killed every Mystic we  had. I don't want to go through that again. I'd rather do without the Community Pack's version of the Artificer.

**Comment by Sklore** [comment]
Ah that's right.

**Pull request merged**
