### PR TITLE
Darkhayze 04092017

### PR DESCRIPTION
**Pull request by DarkHayZe**
Updated descriptions to comply with copy-write

### CODE REVIEW

**Comment by Sklore** [comment]
Really great to have you onboard @DarkHayZe :) It's great seeing another active community member helping out :) thank you so much!

**Comment by DarkHayZe** [comment]
No worries man, I stopped playing for the longest time so I wasn't even following the Community for a while, and when I came back it really felt like the project had died off. So anything I can do to help I am more than happy to do so.

**Comment by Sklore** [comment]
Yeah it's been pretty quiet around here. I've been doing some work for LWD on the Realm Works side of the fence which is taking up most of the time I used to throw at this.

**Comment by DarkHayZe** [comment]
Thats awesome, I saw they were looking for some help for HL... I briefly considered applying but I don't think I have the experience they are looking for. Especially with my lack of scripting knowledge. Also wasn't sure if it paid...lol

**Comment by Sklore** [comment]
I'm just a volunteer. Nothing formal. Helping get them where they need to be.

**Comment by DarkHayZe** [comment]
If I am going to take on something like that, I am going to get paid for it...lol

This though, this helps me more than it does them.

**Comment by Sklore** [comment]
Oh this is benefiting me don't you worry about that ;)

**Pull request merged**
